spring.application.name=EmailConsumer
server.port=8091

# ==========================================
# SQL DB connection config
# ==========================================
spring.datasource.url=jdbc:mysql://localhost:3306/notification_system
spring.datasource.username=lam
spring.datasource.password=
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# ==========================================
# Kafka Connection (Local Docker)
# ==========================================
spring.kafka.bootstrap-servers=127.0.0.1:9092

# ==========================================
# Kafka Consumer Configs
# ==========================================
# Quan tr?ng: M?i consumer (email, sms, push) c?n group-id riêng
spring.kafka.consumer.group-id=email-consumer-group

spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=true
spring.kafka.consumer.auto-commit-interval=5000ms
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Gmail SMTP Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hellomeomoc@gmail.com
# L?u ý: password ? ?ây là "App Password" (m?t kh?u ?ng d?ng), không ph?i m?t kh?u tài kho?n.
spring.mail.password=aero fhzc ytvx vebg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Rate limiting (S? record l?y v? t?i ?a m?i l?n poll)
spring.kafka.consumer.max-poll-records=600